// Code generated by MockGen. DO NOT EDIT.
// Source: internal/crawler/events/eventhandler.go
//
// Generated by this command:
//
//	mockgen -source=internal/crawler/events/eventhandler.go -destination=testutils/mocks/crawler/eventhandler.go -package=crawler
//

// Package crawler is a generated GoMock package.
package crawler

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventHandler is a mock of EventHandler interface.
type MockEventHandler struct {
	ctrl     *gomock.Controller
	recorder *MockEventHandlerMockRecorder
	isgomock struct{}
}

// MockEventHandlerMockRecorder is the mock recorder for MockEventHandler.
type MockEventHandlerMockRecorder struct {
	mock *MockEventHandler
}

// NewMockEventHandler creates a new mock instance.
func NewMockEventHandler(ctrl *gomock.Controller) *MockEventHandler {
	mock := &MockEventHandler{ctrl: ctrl}
	mock.recorder = &MockEventHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventHandler) EXPECT() *MockEventHandlerMockRecorder {
	return m.recorder
}

// HandleError mocks base method.
func (m *MockEventHandler) HandleError(ctx context.Context, err error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleError", ctx, err)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleError indicates an expected call of HandleError.
func (mr *MockEventHandlerMockRecorder) HandleError(ctx, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleError", reflect.TypeOf((*MockEventHandler)(nil).HandleError), ctx, err)
}

// HandleStart mocks base method.
func (m *MockEventHandler) HandleStart(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleStart", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleStart indicates an expected call of HandleStart.
func (mr *MockEventHandlerMockRecorder) HandleStart(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleStart", reflect.TypeOf((*MockEventHandler)(nil).HandleStart), ctx)
}

// HandleStop mocks base method.
func (m *MockEventHandler) HandleStop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleStop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleStop indicates an expected call of HandleStop.
func (mr *MockEventHandlerMockRecorder) HandleStop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleStop", reflect.TypeOf((*MockEventHandler)(nil).HandleStop), ctx)
}
