FROM golang:1.25-alpine

WORKDIR /app

# Install dev tools
RUN apk add --no-cache git ca-certificates

# Writable Go caches
RUN mkdir -p /tmp/go-mod-cache \
             /tmp/go-build-cache && \
    chmod 1777 /tmp/go-mod-cache \
                /tmp/go-build-cache

# Copy go.mod files (source will be bind-mounted)
COPY go.mod go.sum ./

EXPOSE 8090

# Go cache locations
ENV GOCACHE=/tmp/go-build-cache
ENV GOMODCACHE=/tmp/go-mod-cache

# Default dev command
CMD ["sh", "-c", "go mod download && go run -mod=mod ./cmd/httpd/main.go"]
