version: '3'

# Each module resolves dependencies from its own go.mod, not the workspace

vars:
  BINARY_NAME: index-manager
  MAIN_PATH: .

env:
  GOWORK: "off"

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list

  build:
    desc: "Build the index-manager binary"
    sources:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "../infrastructure/**/*.go"
    generates:
      - "bin/{{.BINARY_NAME}}"
    cmds:
      - go build -o bin/{{.BINARY_NAME}} {{.MAIN_PATH}}

  run:
    desc: "Run the index-manager service"
    cmds:
      - go run {{.MAIN_PATH}}

  test:
    desc: "Run all tests"
    sources:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "../infrastructure/**/*.go"
    cmds:
      - go test -v ./...

  test:unit:
    desc: "Run unit tests"
    cmds:
      - go test -v ./internal/...

  test:integration:
    desc: "Run integration tests"
    cmds:
      - go test -v ./tests/integration/...

  test:coverage:
    desc: "Run tests with coverage"
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - 'echo "Coverage report generated: coverage.html"'

  test:race:
    desc: "Run tests with race detector"
    cmds:
      - go test -race ./...

  vuln:
    desc: "Run vulnerability check"
    sources:
      - "go.mod"
      - "go.sum"
    cmds:
      - govulncheck ./...

  vendor:
    desc: Sync vendor directory (run after go get or go mod tidy)
    cmds:
      - go mod vendor

  lint:
    desc: "Lint the Go code"
    sources:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "../.golangci.yml"
      - "../infrastructure/**/*.go"
    cmds:
      - go fmt ./...
      - go vet ./...
      - golangci-lint run --config ../.golangci.yml ./...

  fmt:
    desc: "Format code"
    cmds:
      - go fmt ./...
      - goimports -w .

  tidy:
    desc: "Tidy go.mod and go.sum"
    cmds:
      - go mod tidy

  clean:
    desc: "Clean build artifacts"
    cmds:
      - rm -rf bin/
      - rm -f coverage.out coverage.html

  docker:build:
    desc: "Build Docker image"
    cmds:
      - docker build -t north-cloud-index-manager:latest .

  docker:build:dev:
    desc: "Build development Docker image"
    cmds:
      - docker build -f Dockerfile.dev -t north-cloud-index-manager:dev .

  migrate:up:
    desc: "Run database migrations up"
    silent: true
    cmds:
      - ../scripts/run-migration.sh index-manager up

  migrate:down:
    desc: "Rollback last migration"
    silent: true
    cmds:
      - ../scripts/run-migration.sh index-manager down

  migrate:version:
    desc: "Show current migration version"
    silent: true
    cmds:
      - ../scripts/run-migration.sh index-manager version

  migrate:check:
    desc: "Check if migrations have been applied"
    silent: true
    cmds:
      - ../scripts/run-migration.sh index-manager version || echo "No migrations applied yet. Run 'task migrate:up' to apply migrations."

  migrate:force:
    desc: "Force database to a specific migration version (use to fix dirty state)"
    silent: true
    cmds:
      - |
        if [ -z "{{.VERSION}}" ]; then
          echo "VERSION environment variable not set. Usage: VERSION=1 task migrate:force"
          echo "This will force the database to the specified version (marking it as clean if dirty)"
          exit 1
        fi
      - ../scripts/run-migration.sh index-manager force {{.VERSION}}

  db:shell:
    desc: "Open PostgreSQL shell"
    env:
      PGPASSWORD: '{{.POSTGRES_INDEX_MANAGER_PASSWORD | default ""}}'
    cmds:
      - psql -h {{.POSTGRES_INDEX_MANAGER_HOST | default "localhost"}} -p {{.POSTGRES_INDEX_MANAGER_PORT | default "5436"}} -U {{.POSTGRES_INDEX_MANAGER_USER | default "postgres"}} -d {{.POSTGRES_INDEX_MANAGER_DB | default "index_manager"}}

  dev:
    desc: "Run in development mode with hot-reload (requires air)"
    cmds:
      - air

  install:tools:
    desc: "Install development tools"
    cmds:
      - go install github.com/air-verse/air@latest || true
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.8.0 || true
      - go install golang.org/x/tools/cmd/goimports@latest || true

