version: "2"
linters:
  default: standard
  enable:
    # Non-standard linters that provide additional value
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - cyclop
    - depguard
    - dupl
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exptostd
    - exhaustive
    - fatcontext
    - forbidigo
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gomoddirectives
    - goprintffuncname
    - gosec
    - iface
    - intrange
    - lll
    - loggercheck
    - makezero
    - mirror
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - tagalign
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - misspell
  settings:
    contextcheck:
      disable: false
      enable-avoid-perf-hit: false
    cyclop:
      max-complexity: 30
      package-average: 10
    depguard:
      rules:
        legacy:
          deny:
            - pkg: github.com/golang/protobuf
              desc: Use google.golang.org/protobuf instead, see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules
            - pkg: github.com/satori/go.uuid
              desc: Use github.com/google/uuid instead, satori's package is not maintained
            - pkg: github.com/gofrs/uuid$
              desc: Use github.com/gofrs/uuid/v5 or later, it was not a go module before v5
        type_aliases:
          files:
            - '!internal/logger/*'
            - '!internal/storage/*'
            - '!internal/sources/*'
            - '!internal/config/*'
            - '!internal/common/*'
          deny:
            - pkg: github.com/jonesrussell/north-cloud/crawler/internal/storage/types.Interface
              desc: Use common.Storage type alias instead of storage.Interface directly
            - pkg: github.com/jonesrussell/north-cloud/crawler/internal/sources.Interface
    errcheck:
      check-type-assertions: true
    errchkjson:
      check-error-variable-names: true
      report-no-exported: false
    exhaustive:
      check:
        - switch
        - map
    exhaustruct:
      exclude:
        - ^net/http.Client$
        - ^net/http.Cookie$
        - ^net/http.Request$
        - ^net/http.Response$
        - ^net/http.Server$
        - ^net/http.Transport$
        - ^net/url.URL$
        - ^os/exec.Cmd$
        - ^reflect.StructField$
        - ^github.com/Shopify/sarama.Config$
        - ^github.com/Shopify/sarama.ProducerMessage$
        - ^github.com/mitchellh/mapstructure.DecoderConfig$
        - ^github.com/prometheus/client_golang/.+Opts$
        - ^github.com/spf13/cobra.Command$
        - ^github.com/spf13/cobra.CompletionOptions$
        - ^github.com/stretchr/testify/mock.Mock$
        - ^github.com/testcontainers/testcontainers-go.+Request$
        - ^github.com/testcontainers/testcontainers-go.FromDockerfile$
        - ^golang.org/x/tools/go/analysis.Analyzer$
        - ^google.golang.org/protobuf/.+Options$
        - ^gopkg.in/yaml.v3.Node$
    funlen:
      lines: 100
      statements: 50
      ignore-comments: true
    gocognit:
      min-complexity: 20
    gochecksumtype:
      default-signifies-exhaustive: false
    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
      disabled-checks:
        - commentFormatting
        - hugeParam
        - ifElseChain
        - octalLiteral
        - singleCaseSwitch
        - valSwap
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        shadow:
          strict: true
    inamedparam:
      skip-single-param: true
    lll:
      line-length: 150
    mnd:
      ignored-functions:
        - args.Error
        - flag.Arg
        - flag.Duration.*
        - flag.Float.*
        - flag.Int.*
        - flag.Uint.*
        - os.Chmod
        - os.Mkdir.*
        - os.OpenFile
        - os.WriteFile
        - prometheus.ExponentialBuckets.*
        - prometheus.LinearBuckets
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-no-explanation:
        - funlen
        - gocognit
        - lll
    perfsprint:
      strconcat: false
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    reassign:
      patterns:
        - .*
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
        - name: package-comments
        - name: use-any
          severity: warning
          disabled: false
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
    sloglint:
      no-global: all
      context: scope
    staticcheck:
      checks:
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
        - -ST1023
        - all
      initialisms:
        - ACL
        - API
        - ASCII
        - CPU
        - CSS
        - DNS
        - EOF
        - GUID
        - HTML
        - HTTP
        - HTTPS
        - ID
        - IP
        - JSON
        - QPS
        - RAM
        - RPC
        - SLA
        - SMTP
        - SQL
        - SSH
        - TCP
        - TLS
        - TTL
        - UDP
        - UI
        - GID
        - UID
        - UUID
        - URI
        - URL
        - UTF8
        - VM
        - XML
        - XMPP
        - XSRF
        - XSS
    gosec:
      excludes:
        - G404  # Insecure random number source (math/rand)
        - G402  # TLS InsecureSkipVerify (intentional for development)
    forbidigo:
      forbid:
        - pattern: '^os\.Getenv$'
          msg: 'Use infrastructure/config package instead of direct os.Getenv calls. The config package automatically loads .env files and provides type-safe configuration via struct tags.'
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - godot
        source: (noinspection|TODO)
      - linters:
          - gocritic
        source: //noinspection
      - linters:
          - bodyclose
          - dupl
          - errcheck
          - funlen
          - goconst
          - gosec
          - noctx
          - wrapcheck
        path: _test\.go
      - linters:
          - lll
        path: .*_bench_test\.go$
      - linters:
          - forbidigo
        path: cmd/.*\.go
      - linters:
          - forbidigo
        path: infrastructure/config/.*\.go
      - linters:
          - testpackage
        path: internal/(config|logger)/.*_test\.go
      - linters:
          - canonicalheader
        path: .*/(drupal|publisher)/.*client\.go
        text: (API-KEY|AUTH-METHOD|X-CSRF-Token)
      - linters:
          - mnd
        path: .*/(drupal|publisher)/.*client\.go
        text: (30|400)
      - linters:
          - mnd
        path: .*/config/config\.go
        text: "5"
      - linters:
          - mnd
        path: .*/integration/service\.go
        text: (5|100)
      - linters:
          - unparam
        path: .*/integration/service\.go
        text: runOnce.*always nil
      - linters:
          - nestif
        path: .*/integration/service\.go
      - linters:
          - testableexamples
        path: .*/logger/example_test\.go
      - linters:
          - govet
        path: .*/(config|drupal|integration|publisher)/.*\.go
        text: "shadow"
      - linters:
          - gocritic
        path: (main|cmd/.*/main)\.go
        text: "exitAfterDefer"
      - linters:
          - funlen
          - gocognit
        path: .*/(integration|drupal|publisher)/.*\.go
      - linters:
          - contextcheck
        path: .*/(crawler|scheduler)/.*\.go
      - linters:
          - gochecknoglobals
        path: .*module\.go$
      - linters:
          - gocritic
        text: Use common.Logger type alias instead of logger.Interface directly
      - linters:
          - gocritic
        text: Use common.Storage type alias instead of storage.Interface directly
      - linters:
          - gocritic
        text: Use common.Config type alias instead of config.Config directly
      - linters:
          - gomoddirectives
        path: go\.mod$
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 50
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
