version: '3'

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list

  lint:
    desc: "Run linters for all microservices sequentially"
    cmds:
      - task: lint:auth
      - task: lint:classifier
      - task: lint:crawler
      - task: lint:dashboard
      - task: lint:index-manager
      - task: lint:mcp-north-cloud
      - task: lint:publisher
      - task: lint:search
      - task: lint:search-frontend
      - task: lint:source-manager

  lint:parallel:
    desc: "Run linters for all microservices in parallel"
    cmds:
      - task: lint:auth
      - task: lint:classifier
      - task: lint:crawler
      - task: lint:dashboard
      - task: lint:index-manager
      - task: lint:mcp-north-cloud
      - task: lint:publisher
      - task: lint:search
      - task: lint:search-frontend
      - task: lint:source-manager

  lint:classifier:
    desc: "Run linter for classifier service"
    dir: classifier
    cmds:
      - task lint

  lint:crawler:
    desc: "Run linter for crawler service"
    dir: crawler
    cmds:
      - task lint

  lint:dashboard:
    desc: "Run linter for dashboard service"
    dir: dashboard
    cmds:
      - task lint

  lint:index-manager:
    desc: "Run linter for index-manager service"
    dir: index-manager
    cmds:
      - task lint

  lint:mcp-north-cloud:
    desc: "Run linter for mcp-north-cloud service"
    dir: mcp-north-cloud
    cmds:
      - task lint

  lint:publisher:
    desc: "Run linter for publisher service"
    dir: publisher
    cmds:
      - task lint

  lint:search:
    desc: "Run linter for search service"
    dir: search
    cmds:
      - task lint

  lint:source-manager:
    desc: "Run linter for source-manager service"
    dir: source-manager
    cmds:
      - task lint

  lint:auth:
    desc: "Run linter for auth service"
    dir: auth
    cmds:
      - task lint

  lint:search-frontend:
    desc: "Run linter for search-frontend service"
    dir: search-frontend
    cmds:
      - task lint

  test:
    desc: "Run tests for all microservices sequentially"
    cmds:
      - task: test:auth
      - task: test:classifier
      - task: test:crawler
      - task: test:dashboard
      - task: test:index-manager
      - task: test:publisher
      - task: test:search
      - task: test:search-frontend
      - task: test:source-manager

  test:parallel:
    desc: "Run tests for all microservices in parallel"
    cmds:
      - task: test:auth
      - task: test:classifier
      - task: test:crawler
      - task: test:dashboard
      - task: test:index-manager
      - task: test:publisher
      - task: test:search
      - task: test:search-frontend
      - task: test:source-manager

  test:classifier:
    desc: "Run tests for classifier service"
    dir: classifier
    cmds:
      - task test

  test:crawler:
    desc: "Run tests for crawler service"
    dir: crawler
    cmds:
      - task test

  test:dashboard:
    desc: "Run tests for dashboard service"
    dir: dashboard
    cmds:
      - task test

  test:index-manager:
    desc: "Run tests for index-manager service"
    dir: index-manager
    cmds:
      - task test

  test:publisher:
    desc: "Run tests for publisher service"
    dir: publisher
    cmds:
      - task test

  test:search:
    desc: "Run tests for search service"
    dir: search
    cmds:
      - task test

  test:source-manager:
    desc: "Run tests for source-manager service"
    dir: source-manager
    cmds:
      - task test

  test:auth:
    desc: "Run tests for auth service"
    dir: auth
    cmds:
      - task test

  test:search-frontend:
    desc: "Run tests for search-frontend service"
    dir: search-frontend
    cmds:
      - task test

  test:race:
    desc: "Run tests with race detector for all microservices sequentially"
    cmds:
      - task: test:race:auth
      - task: test:race:classifier
      - task: test:race:crawler
      - task: test:race:dashboard
      - task: test:race:index-manager
      - task: test:race:publisher
      - task: test:race:search
      - task: test:race:search-frontend
      - task: test:race:source-manager

  test:race:parallel:
    desc: "Run tests with race detector for all microservices in parallel"
    cmds:
      - task: test:race:auth
      - task: test:race:classifier
      - task: test:race:crawler
      - task: test:race:dashboard
      - task: test:race:index-manager
      - task: test:race:publisher
      - task: test:race:search
      - task: test:race:search-frontend
      - task: test:race:source-manager

  test:race:auth:
    desc: "Run tests with race detector for auth service"
    dir: auth
    cmds:
      - task test:race
    ignore_error: true

  test:race:classifier:
    desc: "Run tests with race detector for classifier service"
    dir: classifier
    cmds:
      - task test:race
    ignore_error: true

  test:race:crawler:
    desc: "Run tests with race detector for crawler service"
    dir: crawler
    cmds:
      - task test:race
    ignore_error: true

  test:race:dashboard:
    desc: "Run tests with race detector for dashboard service"
    dir: dashboard
    cmds:
      - task test:race
    ignore_error: true

  test:race:index-manager:
    desc: "Run tests with race detector for index-manager service"
    dir: index-manager
    cmds:
      - task test:race
    ignore_error: true

  test:race:publisher:
    desc: "Run tests with race detector for publisher service"
    dir: publisher
    cmds:
      - task test:race

  test:race:search:
    desc: "Run tests with race detector for search service"
    dir: search
    cmds:
      - task test:race
    ignore_error: true

  test:race:search-frontend:
    desc: "Run tests with race detector for search-frontend service"
    dir: search-frontend
    cmds:
      - task test:race
    ignore_error: true

  test:race:source-manager:
    desc: "Run tests with race detector for source-manager service"
    dir: source-manager
    cmds:
      - task test:race

  test:cover:
    desc: "Run tests with coverage for all microservices sequentially"
    cmds:
      - task: test:cover:auth
      - task: test:cover:classifier
      - task: test:cover:crawler
      - task: test:cover:dashboard
      - task: test:cover:index-manager
      - task: test:cover:publisher
      - task: test:cover:search
      - task: test:cover:search-frontend
      - task: test:cover:source-manager

  test:cover:parallel:
    desc: "Run tests with coverage for all microservices in parallel"
    cmds:
      - task: test:cover:auth
      - task: test:cover:classifier
      - task: test:cover:crawler
      - task: test:cover:dashboard
      - task: test:cover:index-manager
      - task: test:cover:publisher
      - task: test:cover:search
      - task: test:cover:search-frontend
      - task: test:cover:source-manager

  test:cover:auth:
    desc: "Run tests with coverage for auth service"
    dir: auth
    cmds:
      - task test:coverage

  test:cover:classifier:
    desc: "Run tests with coverage for classifier service"
    dir: classifier
    cmds:
      - task test:coverage

  test:cover:crawler:
    desc: "Run tests with coverage for crawler service"
    dir: crawler
    cmds:
      - task test:coverage

  test:cover:dashboard:
    desc: "Run tests with coverage for dashboard service"
    dir: dashboard
    cmds:
      - task test:coverage

  test:cover:index-manager:
    desc: "Run tests with coverage for index-manager service"
    dir: index-manager
    cmds:
      - task test:coverage

  test:cover:publisher:
    desc: "Run tests with coverage for publisher service"
    dir: publisher
    cmds:
      - task test:coverage

  test:cover:search:
    desc: "Run tests with coverage for search service"
    dir: search
    cmds:
      - task test:coverage

  test:cover:search-frontend:
    desc: "Run tests with coverage for search-frontend service"
    dir: search-frontend
    cmds:
      - task test:coverage

  test:cover:source-manager:
    desc: "Run tests with coverage for source-manager service"
    dir: source-manager
    cmds:
      - task test:coverage

  docker:dev:up:
    desc: "Start development environment"
    cmds:
      - docker compose -f docker-compose.base.yml -f docker-compose.dev.yml up -d {{.CLI_ARGS}}

  docker:dev:down:
    desc: "Stop development environment"
    cmds:
      - docker compose -f docker-compose.base.yml -f docker-compose.dev.yml down {{.CLI_ARGS}}

  docker:dev:logs:
    desc: "View development environment logs"
    cmds:
      - docker compose -f docker-compose.base.yml -f docker-compose.dev.yml logs -f

  docker:dev:restart:
    desc: "Restart development environment"
    cmds:
      - task: docker:dev:down
      - task: docker:dev:up

  docker:dev:build:
    desc: "Build development Docker images"
    cmds:
      - docker compose -f docker-compose.base.yml -f docker-compose.dev.yml build {{.CLI_ARGS}}

  docker:prod:up:
    desc: "Start production environment"
    cmds:
      - docker compose -f docker-compose.base.yml -f docker-compose.prod.yml up -d {{.CLI_ARGS}}

  docker:prod:down:
    desc: "Stop production environment"
    cmds:
      - docker compose -f docker-compose.base.yml -f docker-compose.prod.yml down {{.CLI_ARGS}}

  docker:prod:logs:
    desc: "View production environment logs"
    cmds:
      - docker compose -f docker-compose.base.yml -f docker-compose.prod.yml logs -f {{.CLI_ARGS}}

  docker:prod:restart:
    desc: "Restart production environment"
    cmds:
      - task: docker:prod:down
      - task: docker:prod:up

  docker:prod:build:
    desc: "Build production Docker images"
    cmds:
      - docker compose -f docker-compose.base.yml -f docker-compose.prod.yml build {{.CLI_ARGS}}

  migrate:up:
    desc: "Run database migrations for all microservices sequentially"
    cmds:
      - task: migrate:crawler
      - task: migrate:source-manager
      - task: migrate:classifier
      - task: migrate:publisher

  migrate:down:
    desc: "Rollback last migration for all microservices sequentially"
    cmds:
      - task: migrate:down:crawler
      - task: migrate:down:source-manager
      - task: migrate:down:classifier
      - task: migrate:down:publisher

  migrate:version:
    desc: "Show migration version for all microservices"
    cmds:
      - task: migrate:version:crawler
      - task: migrate:version:source-manager
      - task: migrate:version:classifier
      - task: migrate:version:publisher

  migrate:crawler:
    desc: "Run database migrations for crawler service"
    dir: crawler
    cmds:
      - task migrate:up

  migrate:down:crawler:
    desc: "Rollback last migration for crawler service"
    dir: crawler
    cmds:
      - task migrate:down

  migrate:version:crawler:
    desc: "Show migration version for crawler service"
    dir: crawler
    cmds:
      - task migrate:version

  migrate:source-manager:
    desc: "Run database migrations for source-manager service"
    dir: source-manager
    cmds:
      - task migrate:up

  migrate:down:source-manager:
    desc: "Rollback last migration for source-manager service"
    dir: source-manager
    cmds:
      - task migrate:down

  migrate:version:source-manager:
    desc: "Show migration version for source-manager service"
    dir: source-manager
    cmds:
      - task migrate:version

  migrate:force:source-manager:
    desc: "Force source-manager database to a specific migration version (use to fix dirty state)"
    dir: source-manager
    cmds:
      - task migrate:force

  migrate:classifier:
    desc: "Run database migrations for classifier service"
    dir: classifier
    cmds:
      - task migrate:up

  migrate:down:classifier:
    desc: "Rollback last migration for classifier service"
    dir: classifier
    cmds:
      - task migrate:down

  migrate:version:classifier:
    desc: "Show migration version for classifier service"
    dir: classifier
    cmds:
      - task migrate:version

  migrate:force:classifier:
    desc: "Force classifier database to a specific migration version (use to fix dirty state)"
    dir: classifier
    cmds:
      - task migrate:force

  migrate:publisher:
    desc: "Run database migrations for publisher service"
    dir: publisher
    cmds:
      - task migrate:up

  migrate:down:publisher:
    desc: "Rollback last migration for publisher service"
    dir: publisher
    cmds:
      - task migrate:down

  migrate:version:publisher:
    desc: "Show migration version for publisher service"
    dir: publisher
    cmds:
      - task migrate:version

  config:init:
    desc: "Copy all config.yml.example files to config.yml"
    cmds:
      - cp auth/config.yml.example auth/config.yml
      - cp classifier/config.yml.example classifier/config.yml
      - cp index-manager/config.yml.example index-manager/config.yml
      - cp publisher/config.yml.example publisher/config.yml
      - cp search/config.yml.example search/config.yml
      - cp source-manager/config.yml.example source-manager/config.yml

  install:tools:
    desc: "Install development tools"
    cmds:
      - go install github.com/air-verse/air@latest || true
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest || true
      - go install golang.org/x/tools/cmd/goimports@latest || true
      - go install github.com/golang-migrate/migrate/v4/cmd/migrate@latest || true
