version: '3'

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list

  lint:
    desc: "Run linters for all microservices sequentially"
    cmds:
      - task: lint:classifier
      - task: lint:crawler
      - task: lint:index-manager
      - task: lint:publisher
      - task: lint:source-manager

  lint:parallel:
    desc: "Run linters for all microservices in parallel"
    cmds:
      - task: lint:classifier
      - task: lint:crawler
      - task: lint:index-manager
      - task: lint:publisher
      - task: lint:source-manager
    run: parallel

  lint:classifier:
    desc: "Run linter for classifier service"
    dir: classifier
    cmds:
      - task lint

  lint:crawler:
    desc: "Run linter for crawler service"
    dir: crawler
    cmds:
      - task lint

  lint:index-manager:
    desc: "Run linter for index-manager service"
    dir: index-manager
    cmds:
      - task lint

  lint:publisher:
    desc: "Run linter for publisher service"
    dir: publisher
    cmds:
      - task lint

  lint:source-manager:
    desc: "Run linter for source-manager service"
    dir: source-manager
    cmds:
      - task lint

  docker:dev:up:
    desc: "Start development environment"
    cmds:
      - docker compose -f docker-compose.base.yml -f docker-compose.dev.yml up -d

  docker:dev:down:
    desc: "Stop development environment"
    cmds:
      - docker compose -f docker-compose.base.yml -f docker-compose.dev.yml down

  docker:dev:logs:
    desc: "View development environment logs"
    cmds:
      - docker compose -f docker-compose.base.yml -f docker-compose.dev.yml logs -f

  docker:dev:restart:
    desc: "Restart development environment"
    cmds:
      - task: docker:dev:down
      - task: docker:dev:up

  docker:prod:up:
    desc: "Start production environment"
    cmds:
      - docker compose -f docker-compose.base.yml -f docker-compose.prod.yml up -d

  docker:prod:down:
    desc: "Stop production environment"
    cmds:
      - docker compose -f docker-compose.base.yml -f docker-compose.prod.yml down

  docker:prod:logs:
    desc: "View production environment logs"
    cmds:
      - docker compose -f docker-compose.base.yml -f docker-compose.prod.yml logs -f

  docker:prod:restart:
    desc: "Restart production environment"
    cmds:
      - task: docker:prod:down
      - task: docker:prod:up
