version: '3'

dotenv: ['../.env']

vars:
  BINARY_NAME: search
  MAIN_PATH: ./cmd/httpd/main.go

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list

  build:
    desc: "Build the search binary"
    cmds:
      - go build -o bin/{{.BINARY_NAME}} {{.MAIN_PATH}}

  run:
    desc: "Run the search service"
    cmds:
      - go run {{.MAIN_PATH}}

  test:
    desc: "Run all tests"
    cmds:
      - go test -v ./...

  test:unit:
    desc: "Run unit tests"
    cmds:
      - go test -v ./internal/...

  test:integration:
    desc: "Run integration tests"
    cmds:
      - go test -v ./tests/integration/...

  test:coverage:
    desc: "Run tests with coverage"
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - 'echo "Coverage report generated: coverage.html"'

  lint:
    desc: "Lint the Go code"
    cmds:
      - go fmt ./...
      - go vet ./...
      - golangci-lint run || true

  fmt:
    desc: "Format code"
    cmds:
      - go fmt ./...
      - goimports -w . || true

  tidy:
    desc: "Tidy go.mod and go.sum"
    cmds:
      - go mod tidy

  clean:
    desc: "Clean build artifacts"
    cmds:
      - rm -rf bin/
      - rm -f coverage.out coverage.html

  docker:build:
    desc: "Build Docker image"
    cmds:
      - docker build -t north-cloud-search:latest -f Dockerfile ..

  docker:build:dev:
    desc: "Build development Docker image"
    cmds:
      - docker build -f Dockerfile.dev -t north-cloud-search:dev .

  docker:run:
    desc: "Run search service in Docker (development)"
    cmds:
      - docker-compose -f ../docker-compose.base.yml -f ../docker-compose.dev.yml up -d search-service

  docker:logs:
    desc: "View search service logs"
    cmds:
      - docker-compose -f ../docker-compose.base.yml -f ../docker-compose.dev.yml logs -f search-service

  docker:stop:
    desc: "Stop search service"
    cmds:
      - docker-compose -f ../docker-compose.base.yml -f ../docker-compose.dev.yml stop search-service

  dev:
    desc: "Run in development mode with hot-reload (requires air)"
    cmds:
      - air

  install:tools:
    desc: "Install development tools"
    cmds:
      - go install github.com/air-verse/air@latest || true
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest || true
      - go install golang.org/x/tools/cmd/goimports@latest || true

  health:
    desc: "Check search service health"
    cmds:
      - curl -f http://localhost:8092/health || echo "Service not responding"

  search:
    desc: "Test search endpoint with sample query"
    cmds:
      - |
        curl -X POST http://localhost:8092/api/v1/search \
          -H "Content-Type: application/json" \
          -d '{"query": "crime", "pagination": {"page": 1, "size": 5}}' | jq .
