version: '3'

output:
  group:
    error_only: false
  colorize: true
  prefix:
    info: "🔍"
    success: "✅"
    warning: "⚠️"
    error: "❌"


tasks:
  default:
    desc: "Show help and list common tasks"
    cmds:
      - task: build
  api:
    desc: "Run the HTTP API server"
    cmds:
      - go run main.go
    ignore_error: true
    interactive: true

  build:
    desc: "Build the web crawler executable"
    cmds:
      - mkdir -p bin
      - go build -o bin/crawler main.go

  run:
    desc: "Run the crawler service"
    cmds:
      - go run main.go

  deadcode:
    desc: "Find unreachable functions in the codebase"
    cmds:
      - deadcode -test -generated ./...
    ignore_error: true



  lint:
    desc: "Lint the Go code"
    cmds:
      - go fmt ./...
      - go vet ./...
      - golangci-lint run {{.CLI_ARGS}}

  test:
    desc: "Run all tests"
    cmds:
      - go test -v ./...

  test:unit:
    desc: "Run unit tests"
    cmds:
      - go test -v ./internal/...

  test:integration:
    desc: "Run integration tests"
    cmds:
      - go test -v ./tests/integration/...

  test:features:
    desc: "Run feature tests"
    cmds:
      - go test -v ./tests/features/...

  test:coverage:
    desc: "Run tests with coverage"
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - 'echo "Coverage report generated: coverage.html"'


  generate:
    desc: Generate code (mocks, etc.)
    cmds:
      - ./scripts/generate_mocks.sh

  fmt:
    desc: "Format code"
    cmds:
      - go fmt ./...
      - goimports -w . || true

  tidy:
    desc: "Tidy go.mod and go.sum"
    cmds:
      - go mod tidy

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - rm -rf testutils/mocks/
      - rm -f coverage.out coverage.html

  dev:
    desc: "Run in development mode with hot-reload (requires air)"
    cmds:
      - air

  install:tools:
    desc: "Install development tools"
    cmds:
      - go install github.com/air-verse/air@latest || true
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest || true
      - go install golang.org/x/tools/cmd/goimports@latest || true

  docker:build:
    desc: "Build Docker image"
    cmds:
      - docker build -t north-cloud-crawler:latest .

  docker:build:dev:
    desc: "Build development Docker image"
    cmds:
      - docker build -f Dockerfile.dev -t north-cloud-crawler:dev .

