version: '3'

dotenv: ['../.env']

output:
  group:
    error_only: false
  colorize: true
  prefix:
    info: "🔍"
    success: "✅"
    warning: "⚠️"
    error: "❌"


tasks:
  default:
    desc: "Show help and list common tasks"
    cmds:
      - task: build
  api:
    desc: "Run the HTTP API server"
    cmds:
      - go run main.go
    ignore_error: true
    interactive: true

  build:
    desc: "Build the web crawler executable"
    cmds:
      - mkdir -p bin
      - go build -o bin/crawler main.go

  run:
    desc: "Run the crawler service"
    cmds:
      - go run main.go

  deadcode:
    desc: "Find unreachable functions in the codebase"
    cmds:
      - deadcode -test -generated ./...
    ignore_error: true



  lint:
    desc: "Lint the Go code"
    cmds:
      - go fmt ./...
      - go vet ./...
      - golangci-lint run {{.CLI_ARGS}}

  test:
    desc: "Run all tests"
    cmds:
      - go test -v ./...

  test:unit:
    desc: "Run unit tests"
    cmds:
      - go test -v ./internal/...

  test:integration:
    desc: "Run integration tests"
    cmds:
      - go test -v ./tests/integration/...

  test:features:
    desc: "Run feature tests"
    cmds:
      - go test -v ./tests/features/...

  test:coverage:
    desc: "Run tests with coverage"
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - 'echo "Coverage report generated: coverage.html"'


  generate:
    desc: Generate code (mocks, etc.)
    cmds:
      - ./scripts/generate_mocks.sh

  fmt:
    desc: "Format code"
    cmds:
      - go fmt ./...
      - goimports -w . || true

  tidy:
    desc: "Tidy go.mod and go.sum"
    cmds:
      - go mod tidy

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - rm -rf testutils/mocks/
      - rm -f coverage.out coverage.html

  dev:
    desc: "Run in development mode with hot-reload (requires air)"
    cmds:
      - air

  install:tools:
    desc: "Install development tools"
    cmds:
      - go install github.com/air-verse/air@latest || true
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest || true
      - go install golang.org/x/tools/cmd/goimports@latest || true
      - go install github.com/golang-migrate/migrate/v4/cmd/migrate@latest || true

  migrate:up:
    desc: "Run database migrations up"
    silent: true
    env:
      PGPASSWORD: '{{.POSTGRES_CRAWLER_PASSWORD | default ""}}'
    cmds:
      - |
        if [ -z "{{.POSTGRES_CRAWLER_PASSWORD}}" ]; then
          echo "POSTGRES_CRAWLER_PASSWORD environment variable not set"
          exit 1
        fi
      - |
        DB_HOST="{{.POSTGRES_CRAWLER_HOST | default "localhost"}}"
        DB_PORT="{{.POSTGRES_CRAWLER_PORT | default "5432"}}"
        DB_USER="{{.POSTGRES_CRAWLER_USER | default "postgres"}}"
        DB_PASSWORD="{{.POSTGRES_CRAWLER_PASSWORD}}"
        DB_NAME="{{.POSTGRES_CRAWLER_DB | default "crawler"}}"
        
        # Use Docker to run migration if connecting to containerized database
        if [ "$DB_HOST" = "localhost" ] && docker ps --format '{{.Names}}' | grep -q 'north-cloud-postgres-crawler'; then
          echo "Running migration via Docker (connecting to postgres-crawler container)..."
          docker run --rm --network north-cloud_north-cloud-network \
            -v "$(pwd)/migrations:/migrations" \
            migrate/migrate:latest \
            -path /migrations \
            -database "postgres://${DB_USER}:${DB_PASSWORD}@postgres-crawler:5432/${DB_NAME}?sslmode=disable" \
            up
        else
          echo "Running migration via local connection..."
          DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"
          migrate -path ./migrations -database "$DATABASE_URL" up
        fi

  migrate:down:
    desc: "Rollback last migration"
    silent: true
    env:
      PGPASSWORD: '{{.POSTGRES_CRAWLER_PASSWORD | default ""}}'
    cmds:
      - |
        if [ -z "{{.POSTGRES_CRAWLER_PASSWORD}}" ]; then
          echo "POSTGRES_CRAWLER_PASSWORD environment variable not set"
          exit 1
        fi
      - |
        DB_HOST="{{.POSTGRES_CRAWLER_HOST | default "localhost"}}"
        DB_PORT="{{.POSTGRES_CRAWLER_PORT | default "5432"}}"
        DB_USER="{{.POSTGRES_CRAWLER_USER | default "postgres"}}"
        DB_PASSWORD="{{.POSTGRES_CRAWLER_PASSWORD}}"
        DB_NAME="{{.POSTGRES_CRAWLER_DB | default "crawler"}}"
        DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"
        migrate -path ./migrations -database "$DATABASE_URL" down 1

  migrate:version:
    desc: "Show current migration version"
    silent: true
    env:
      PGPASSWORD: '{{.POSTGRES_CRAWLER_PASSWORD | default ""}}'
    cmds:
      - |
        if [ -z "{{.POSTGRES_CRAWLER_PASSWORD}}" ]; then
          echo "POSTGRES_CRAWLER_PASSWORD environment variable not set"
          exit 1
        fi
      - |
        DB_HOST="{{.POSTGRES_CRAWLER_HOST | default "localhost"}}"
        DB_PORT="{{.POSTGRES_CRAWLER_PORT | default "5432"}}"
        DB_USER="{{.POSTGRES_CRAWLER_USER | default "postgres"}}"
        DB_PASSWORD="{{.POSTGRES_CRAWLER_PASSWORD}}"
        DB_NAME="{{.POSTGRES_CRAWLER_DB | default "crawler"}}"
        DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"
        migrate -path ./migrations -database "$DATABASE_URL" version

  migrate:check:
    desc: "Check if migrations have been applied"
    silent: true
    env:
      PGPASSWORD: '{{.POSTGRES_CRAWLER_PASSWORD | default ""}}'
    cmds:
      - |
        if [ -z "{{.POSTGRES_CRAWLER_PASSWORD}}" ]; then
          echo "POSTGRES_CRAWLER_PASSWORD environment variable not set"
          exit 1
        fi
      - |
        DB_HOST="{{.POSTGRES_CRAWLER_HOST | default "localhost"}}"
        DB_PORT="{{.POSTGRES_CRAWLER_PORT | default "5432"}}"
        DB_USER="{{.POSTGRES_CRAWLER_USER | default "postgres"}}"
        DB_PASSWORD="{{.POSTGRES_CRAWLER_PASSWORD}}"
        DB_NAME="{{.POSTGRES_CRAWLER_DB | default "crawler"}}"
        DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"
        migrate -path ./migrations -database "$DATABASE_URL" version || echo "No migrations applied yet. Run 'task migrate:up' to apply migrations."

  docker:build:
    desc: "Build Docker image"
    cmds:
      - docker build -t north-cloud-crawler:latest .

  docker:build:dev:
    desc: "Build development Docker image"
    cmds:
      - docker build -f Dockerfile.dev -t north-cloud-crawler:dev .

