version: '3'

# Each module resolves dependencies from its own go.mod, not the workspace
env:

output:

  group:
    error_only: false

tasks:
  default:
    desc: "Show help and list common tasks"
    cmds:
      - task: build

  api:
    desc: "Run the HTTP API server"
    cmds:
      - go run main.go
    ignore_error: true
    interactive: true

  build:
    desc: "Build the web crawler executable"
    sources:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "../infrastructure/**/*.go"
    generates:
      - "bin/crawler"
    cmds:
      - mkdir -p bin
      - go build -o bin/crawler main.go

  run:
    desc: "Run the crawler service"
    cmds:
      - go run main.go

  deadcode:
    desc: "Find unreachable functions in the codebase"
    cmds:
      - deadcode -test -generated ./...
    ignore_error: true



  lint:
    desc: "Lint the Go code"
    sources:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "../.golangci.yml"
      - "../infrastructure/**/*.go"
    cmds:
      - go fmt ./...
      - go vet ./...
      - golangci-lint run --config ../.golangci.yml ./... {{.CLI_ARGS}}

  lint:no-cache:
    desc: "Run linter with cache disabled (matches CI)"
    cmds:
      - go fmt ./...
      - go vet ./...
      - golangci-lint cache clean
      - golangci-lint run --config ../.golangci.yml ./...

  test:
    desc: "Run all tests"
    sources:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "../infrastructure/**/*.go"
    cmds:
      - go test -v ./...

  test:unit:
    desc: "Run unit tests"
    cmds:
      - go test -v ./internal/...

  test:integration:
    desc: "Run integration tests"
    cmds:
      - go test -v ./tests/integration/...

  test:features:
    desc: "Run feature tests"
    cmds:
      - go test -v ./tests/features/...

  test:coverage:
    desc: "Run tests with coverage"
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - 'echo "Coverage report generated: coverage.html"'

  test:race:
    desc: "Run tests with race detector"
    cmds:
      - go test -race ./...

  vuln:
    desc: "Run vulnerability check"
    sources:
      - "go.mod"
      - "go.sum"
    cmds:
      - govulncheck ./...

  bench:
    desc: "Run benchmarks"
    cmds:
      - go test -bench=. -benchmem ./...

  bench:baseline:
    desc: "Capture performance baseline"
    cmds:
      - mkdir -p benchmarks
      - go test -bench=. -benchmem -benchtime=30s -count=5 ./... | tee benchmarks/baseline-{{now | date "2006-01-02"}}.txt
      - 'echo "Baseline captured: benchmarks/baseline-{{now | date "2006-01-02"}}.txt"'

  bench:compare:
    desc: "Compare current performance to baseline (requires benchstat)"
    cmds:
      - go test -bench=. -benchmem -benchtime=30s -count=5 ./... > benchmarks/current.txt
      - benchstat benchmarks/baseline-*.txt benchmarks/current.txt

  bench:profile:
    desc: "Run benchmarks with CPU and memory profiling"
    cmds:
      - mkdir -p profiles
      - go test -bench=. -cpuprofile=profiles/cpu.prof -memprofile=profiles/mem.prof ./...
      - 'echo "Profiles saved to profiles/ directory"'
      - 'echo "View CPU profile: go tool pprof -http=:8081 profiles/cpu.prof"'
      - 'echo "View memory profile: go tool pprof -http=:8081 profiles/mem.prof"'


  generate:
    desc: Generate code (mocks, etc.)
    cmds:
      - ./scripts/generate_mocks.sh

  fmt:
    desc: "Format code"
    cmds:
      - go fmt ./...
      - goimports -w . || true

  tidy:
    desc: "Tidy go.mod and go.sum"
    cmds:
      - go mod tidy

  vendor:
    desc: Sync vendor directory (run after go get or go mod tidy)
    cmds:
      - go mod vendor

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - rm -rf testutils/mocks/
      - rm -f coverage.out coverage.html

  dev:
    desc: "Run in development mode with hot-reload (requires air)"
    cmds:
      - air

  install:tools:
    desc: "Install development tools"
    cmds:
      - go install github.com/air-verse/air@latest || true
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.8.0 || true
      - go install golang.org/x/tools/cmd/goimports@latest || true
      - go install github.com/golang-migrate/migrate/v4/cmd/migrate@latest || true

  migrate:up:
    desc: "Run database migrations up"
    silent: true
    cmds:
      - ../scripts/run-migration.sh crawler up

  migrate:down:
    desc: "Rollback last migration"
    silent: true
    cmds:
      - ../scripts/run-migration.sh crawler down

  migrate:version:
    desc: "Show current migration version"
    silent: true
    cmds:
      - ../scripts/run-migration.sh crawler version

  migrate:check:
    desc: "Check if migrations have been applied"
    silent: true
    cmds:
      - ../scripts/run-migration.sh crawler version || echo "No migrations applied yet. Run 'task migrate:up' to apply migrations."

  migrate:force:
    desc: "Force crawler database to a specific migration version (use to fix dirty state)"
    silent: true
    cmds:
      - |
        if [ -z "{{.VERSION}}" ]; then
          echo "VERSION environment variable not set. Usage: VERSION=5 task migrate:force"
          echo "This will force the database to the specified version (marking it as clean if dirty)"
          exit 1
        fi
      - ../scripts/run-migration.sh crawler force {{.VERSION}}

  docker:build:
    desc: "Build Docker image"
    cmds:
      - docker build -t north-cloud-crawler:latest .

  docker:build:dev:
    desc: "Build development Docker image"
    cmds:
      - docker build -f Dockerfile.dev -t north-cloud-crawler:dev .

