version: '3'

dotenv: ['../.env']

vars:
  BINARY_NAME: auth
  MAIN_PATH: ./main.go

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list

  build:
    desc: "Build the auth binary"
    cmds:
      - go build -o bin/{{.BINARY_NAME}} {{.MAIN_PATH}}

  run:
    desc: "Run the auth service"
    cmds:
      - go run {{.MAIN_PATH}}

  test:
    desc: "Run all tests"
    cmds:
      - go test -v ./...

  test:unit:
    desc: "Run unit tests"
    cmds:
      - go test -v ./internal/...

  test:coverage:
    desc: "Run tests with coverage"
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - 'echo "Coverage report generated: coverage.html"'

  lint:
    desc: "Lint the Go code"
    cmds:
      - go fmt ./...
      - go vet ./...
      - golangci-lint run || true

  fmt:
    desc: "Format code"
    cmds:
      - go fmt ./...
      - goimports -w . || true

  tidy:
    desc: "Tidy go.mod and go.sum"
    cmds:
      - go mod tidy

  clean:
    desc: "Clean build artifacts"
    cmds:
      - rm -rf bin/
      - rm -f coverage.out coverage.html

  docker:build:
    desc: "Build Docker image"
    cmds:
      - docker build -t north-cloud-auth:latest .

  docker:build:dev:
    desc: "Build development Docker image"
    cmds:
      - docker build -f Dockerfile.dev -t north-cloud-auth:dev .

  install:tools:
    desc: "Install development tools"
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest || true
      - go install golang.org/x/tools/cmd/goimports@latest || true

