version: '3'

# Each module resolves dependencies from its own go.mod, not the workspace
env:
  GOWORK: "off"

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list

  build:
    desc: Build the proxy binary
    sources:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "../infrastructure/**/*.go"
    generates:
      - "bin/nc-http-proxy"
    cmds:
      - go build -o bin/nc-http-proxy .

  test:
    desc: Run tests
    sources:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "../infrastructure/**/*.go"
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - 'echo "Coverage report generated: coverage.html"'

  test:race:
    desc: Run tests with race detector
    cmds:
      - go test -race ./...

  vuln:
    desc: Run vulnerability check
    sources:
      - "go.mod"
      - "go.sum"
    cmds:
      - govulncheck ./...

  vendor:
    desc: Sync vendor directory (run after go get or go mod tidy)
    cmds:
      - go mod vendor

  lint:
    desc: Run linter
    sources:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "../.golangci.yml"
      - "../infrastructure/**/*.go"
    cmds:
      - go fmt ./...
      - go vet ./...
      - golangci-lint run --config ../.golangci.yml ./...

  lint:no-cache:
    desc: "Run linter with cache disabled (matches CI)"
    cmds:
      - go fmt ./...
      - go vet ./...
      - golangci-lint cache clean
      - golangci-lint run --config ../.golangci.yml ./...

  run:
    desc: Run the proxy locally
    cmds:
      - go run .
