version: '3'

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list

  build:
    desc: Build the proxy binary
    cmds:
      - go build -o bin/nc-http-proxy .

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - 'echo "Coverage report generated: coverage.html"'

  test:race:
    desc: Run tests with race detector
    cmds:
      - go test -race ./...

  vuln:
    desc: Run vulnerability check
    cmds:
      - govulncheck ./...

  vendor:
    desc: Sync vendor directory (run after go get or go mod tidy)
    env: { GOWORK: "off" }
    cmds:
      - go mod vendor

  lint:
    desc: Run linter
    cmds:
      - go fmt ./...
      - go vet ./...
      - golangci-lint run --config ../.golangci.yml ./...

  run:
    desc: Run the proxy locally
    cmds:
      - go run .
