global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'classifier'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['classifier:8071']

  - job_name: 'publisher'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['publisher:8070']

  - job_name: 'search'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['search:8090']

  - job_name: 'index-manager'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['index-manager:8090']

  - job_name: 'auth'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth:8040']

  - job_name: 'crawler'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['crawler:8080']

  - job_name: 'source-manager'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['source-manager:8050']

  - job_name: 'pipeline'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['pipeline:8075']

  - job_name: 'click-tracker'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['click-tracker:8093']

  - job_name: 'rfp-ingestor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rfp-ingestor:8095']
