version: '3'

vars:
  BINARY_NAME: gosources
  MAIN_PATH: ./main.go
  BUILD_DIR: ./bin
  DOCKER_IMAGE: gosources
  CONFIG_FILE: config.yml
  DB_HOST: localhost
  DB_PORT: 5432
  DB_USER: postgres
  DB_NAME: gosources

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the gosources service
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.MAIN_PATH}}
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  run:
    desc: Run the service locally
    deps: [deps]
    cmds:
      - go run {{.MAIN_PATH}} -config {{.CONFIG_FILE}}

  test:
    desc: Run all tests
    deps: [deps]
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage report
    deps: [deps]
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - 'echo "Coverage report generated: coverage.html"'

  test:race:
    desc: Run tests with race detector
    deps: [deps]
    cmds:
      - go test -race ./...

  clean:
    desc: Clean build artifacts and temporary files
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f coverage.out coverage.html
      - go clean -cache -testcache -modcache

  deps:
    desc: Download and tidy dependencies
    cmds:
      - go mod download
      - go mod tidy
      - go mod verify

  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  lint:
    desc: Run golangci-lint (if installed)
    cmds:
      - task: fmt
      - task: vet
      - golangci-lint run

  check:
    desc: Run all code quality checks (fmt, vet, lint)
    cmds:
      - task: fmt
      - task: vet
      - task: lint

  migrate:
    desc: Run database migrations
    cmds:
      - |
        if [ -z "$DB_PASSWORD" ]; then
          echo "DB_PASSWORD environment variable not set"
          exit 1
        fi
      - |
        PGPASSWORD={{.DB_PASSWORD}} psql -h {{.DB_HOST}} -p {{.DB_PORT}} -U {{.DB_USER}} -d {{.DB_NAME}} -f migrations/001_create_sources_table.sql

  migrate:check:
    desc: Check if migrations have been applied
    cmds:
      - |
        if [ -z "$DB_PASSWORD" ]; then
          echo "DB_PASSWORD environment variable not set"
          exit 1
        fi
      - |
        PGPASSWORD={{.DB_PASSWORD}} psql -h {{.DB_HOST}} -p {{.DB_PORT}} -U {{.DB_USER}} -d {{.DB_NAME}} -c "\d sources" || echo "Table 'sources' does not exist. Run 'task migrate' to create it."

  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t {{.DOCKER_IMAGE}} .

  docker:up:
    desc: Start services with Docker Compose
    cmds:
      - docker compose -f docker-compose.yml up -d

  docker:down:
    desc: Stop services
    cmds:
      - docker compose -f docker-compose.yml down

  docker:logs:
    desc: View gosources service logs
    cmds:
      - docker compose -f docker-compose.yml logs -f gosources

  docker:restart:
    desc: Restart Docker services
    cmds:
      - task: docker:down
      - task: docker:up

  docker:migrate:
    desc: Run migrations in Docker environment
    cmds:
      - docker compose -f docker-compose.yml exec -T postgres psql -U postgres -d gosources < migrations/001_create_sources_table.sql

  air:install:
    desc: Install air for hot reloading
    cmds:
      - |
        if ! command -v air > /dev/null; then
          echo "Installing air..."
          go install github.com/air-verse/air@latest
          echo "✓ air installed successfully"
        else
          echo "✓ air is already installed"
        fi
    status:
      - command -v air > /dev/null

  dev:
    desc: Run backend in development mode with hot reloading
    deps: [air:install]
    cmds:
      - air -c .air.toml

  dev:backend:
    desc: Run backend in development mode with hot reloading (alias for dev)
    deps: [air:install]
    cmds:
      - air -c .air.toml

  dev:all:
    desc: Run both backend and frontend in development mode
    deps: [air:install, frontend:install]
    cmds:
      - |
        echo "Starting backend and frontend in development mode..."
        echo "Backend will run on http://localhost:8050"
        echo "Frontend will run on http://localhost:3000"
        echo ""
        # Run both in background, then wait
        air -c .air.toml &
        BACKEND_PID=$!
        cd frontend && npm run dev &
        FRONTEND_PID=$!

        # Trap to kill both processes on exit
        trap "kill $BACKEND_PID $FRONTEND_PID 2>/dev/null" EXIT

        # Wait for both processes
        wait

  install:
    desc: Install the binary to $GOPATH/bin
    cmds:
      - go install {{.MAIN_PATH}}

  all:
    desc: Run build, test, and check
    cmds:
      - task: deps
      - task: check
      - task: test
      - task: build

  frontend:install:
    desc: Install frontend dependencies
    dir: frontend
    cmds:
      - npm install

  frontend:dev:
    desc: Run frontend development server
    dir: frontend
    cmds:
      - npm run dev

  frontend:build:
    desc: Build frontend for production
    dir: frontend
    cmds:
      - npm run build

  frontend:preview:
    desc: Preview production build
    dir: frontend
    cmds:
      - npm run preview

