version: '3'

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list

  lint:
    desc: "Lint the code"
    cmds:
      - npm run lint || echo "No lint script found"

  test:
    desc: "Run tests (no tests configured)"
    cmds:
      - echo "No tests configured for search-frontend"

  test:coverage:
    desc: "Run tests with coverage (no-op for search-frontend)"
    cmds:
      - echo "No coverage configured for search-frontend"

  test:race:
    desc: "Run tests with race detector (no-op for frontend)"
    cmds:
      - echo "test:race is not applicable for search-frontend"

  build:
    desc: "Build for production"
    cmds:
      - npm run build

  clean:
    desc: "Remove build artifacts"
    cmds:
      - rm -rf dist/

  dev:
    desc: "Run development server"
    cmds:
      - npm run dev

  preview:
    desc: "Preview production build"
    cmds:
      - npm run preview

