// Package database: source candidate repository for the Source Candidate Pipeline.

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/jmoiron/sqlx"
	"github.com/jonesrussell/north-cloud/crawler/internal/discovery"
)

// CandidateRepository persists source candidates for the Source Candidate Pipeline.
type CandidateRepository struct {
	db *sqlx.DB
}

// NewCandidateRepository creates a new candidate repository.
func NewCandidateRepository(db *sqlx.DB) *CandidateRepository {
	return &CandidateRepository{db: db}
}

// Create inserts a new source candidate. ID is generated by the DB.
func (r *CandidateRepository) Create(ctx context.Context, c *discovery.SourceCandidate) error {
	enrichmentJSON, marshalErr := json.Marshal(c.Enrichment)
	if marshalErr != nil {
		return fmt.Errorf("marshal enrichment: %w", marshalErr)
	}
	riskReasonsJSON, reasonsErr := json.Marshal(c.RiskReasons)
	if reasonsErr != nil {
		return fmt.Errorf("marshal risk_reasons: %w", reasonsErr)
	}

	query := `
		INSERT INTO source_candidates
			(canonical_url, identity_key, referring_source_id,
			 enrichment, risk_score, risk_reasons, status,
			 approved_at, approved_by, created_source_id,
			 created_at, updated_at)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
		RETURNING id, created_at, updated_at
	`
	var id string
	var createdAt, updatedAt time.Time
	err := r.db.QueryRowContext(ctx, query,
		c.CanonicalURL, c.IdentityKey, c.ReferringSourceID,
		enrichmentJSON, c.RiskScore, riskReasonsJSON,
		string(c.Status), c.ApprovedAt, nullEmpty(c.ApprovedBy), nullEmpty(c.CreatedSourceID),
		c.CreatedAt, c.UpdatedAt,
	).Scan(&id, &createdAt, &updatedAt)
	if err != nil {
		return fmt.Errorf("insert source_candidate: %w", err)
	}
	c.ID = id
	c.CreatedAt = createdAt
	c.UpdatedAt = updatedAt
	return nil
}

// candidateSelectColumns lists the columns for source_candidates SELECTs.
const candidateSelectColumns = `id, canonical_url, identity_key,
		referring_source_id, enrichment, risk_score, risk_reasons,
		status, approved_at, approved_by, created_source_id,
		created_at, updated_at`

// candidateDBRow is the row type for source_candidates SELECTs.
type candidateDBRow struct {
	ID                string     `db:"id"`
	CanonicalURL      string     `db:"canonical_url"`
	IdentityKey       string     `db:"identity_key"`
	ReferringSourceID string     `db:"referring_source_id"`
	Enrichment        []byte     `db:"enrichment"`
	RiskScore         float64    `db:"risk_score"`
	RiskReasons       []byte     `db:"risk_reasons"`
	Status            string     `db:"status"`
	ApprovedAt        *time.Time `db:"approved_at"`
	ApprovedBy        *string    `db:"approved_by"`
	CreatedSourceID   *string    `db:"created_source_id"`
	CreatedAt         time.Time  `db:"created_at"`
	UpdatedAt         time.Time  `db:"updated_at"`
}

// GetByID returns a candidate by ID, or nil if not found.
func (r *CandidateRepository) GetByID(ctx context.Context, id string) (*discovery.SourceCandidate, error) {
	query := `SELECT ` + candidateSelectColumns + `
		FROM source_candidates WHERE id = $1`
	var row candidateDBRow
	err := r.db.GetContext(ctx, &row, query, id)
	if err != nil {
		if isNoRows(err) {
			return nil, nil //nolint:nilnil // nil,nil = "not found" per interface contract
		}
		return nil, fmt.Errorf("get candidate: %w", err)
	}
	return scanCandidateRow(candidateDBRowToRow(row))
}

// GetPendingByIdentityKey returns a pending candidate with the given identity_key, or nil.
func (r *CandidateRepository) GetPendingByIdentityKey(
	ctx context.Context, identityKey string,
) (*discovery.SourceCandidate, error) {
	query := `SELECT ` + candidateSelectColumns + `
		FROM source_candidates
		WHERE identity_key = $1 AND status = $2`
	var row candidateDBRow
	err := r.db.GetContext(ctx, &row, query, identityKey, string(discovery.CandidateStatusPending))
	if err != nil {
		if isNoRows(err) {
			return nil, nil //nolint:nilnil // nil,nil = "not found" per interface contract
		}
		return nil, fmt.Errorf("get pending candidate by identity_key: %w", err)
	}
	return scanCandidateRow(candidateDBRowToRow(row))
}

const defaultListPendingLimit = 50

// ListPending returns pending candidates, up to limit, for approval queue.
func (r *CandidateRepository) ListPending(ctx context.Context, limit int) ([]*discovery.SourceCandidate, error) {
	return r.ListByStatus(ctx, string(discovery.CandidateStatusPending), limit)
}

// ListByStatus returns candidates with the given status, up to limit.
func (r *CandidateRepository) ListByStatus(ctx context.Context, status string, limit int) ([]*discovery.SourceCandidate, error) {
	if limit <= 0 {
		limit = defaultListPendingLimit
	}
	query := `SELECT ` + candidateSelectColumns + `
		FROM source_candidates
		WHERE status = $1 ORDER BY created_at ASC LIMIT $2`
	var rows []candidateDBRow
	err := r.db.SelectContext(ctx, &rows, query, status, limit)
	if err != nil {
		return nil, fmt.Errorf("list candidates by status: %w", err)
	}
	out := make([]*discovery.SourceCandidate, 0, len(rows))
	for i := range rows {
		c, scanErr := scanCandidateRow(candidateDBRowToRow(rows[i]))
		if scanErr != nil {
			return nil, scanErr
		}
		out = append(out, c)
	}
	return out, nil
}

// UpdateStatus sets status, approved_at, approved_by, and optionally created_source_id.
func (r *CandidateRepository) UpdateStatus(ctx context.Context, id, status string, approvedAt *time.Time, approvedBy, createdSourceID string) error {
	query := `
		UPDATE source_candidates SET status = $1, approved_at = $2, approved_by = $3, created_source_id = NULLIF($4, ''), updated_at = NOW() WHERE id = $5
	`
	result, err := r.db.ExecContext(ctx, query, status, approvedAt, nullEmpty(approvedBy), createdSourceID, id)
	if err != nil {
		return fmt.Errorf("update candidate status: %w", err)
	}
	n, rowsErr := result.RowsAffected()
	if rowsErr != nil {
		return fmt.Errorf("check rows affected for candidate %s: %w", id, rowsErr)
	}
	if n == 0 {
		return fmt.Errorf("candidate not found: %s", id)
	}
	return nil
}

type candidateRow struct {
	ID                string
	CanonicalURL      string
	IdentityKey       string
	ReferringSourceID string
	Enrichment        []byte
	RiskScore         float64
	RiskReasons       []byte
	Status            string
	ApprovedAt        *time.Time
	ApprovedBy        *string
	CreatedSourceID   *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func candidateDBRowToRow(r candidateDBRow) candidateRow {
	return candidateRow(r)
}

func scanCandidateRow(row candidateRow) (*discovery.SourceCandidate, error) {
	var enrichment *discovery.Enrichment
	if len(row.Enrichment) > 0 {
		enrichment = &discovery.Enrichment{}
		if err := json.Unmarshal(row.Enrichment, enrichment); err != nil {
			return nil, fmt.Errorf("unmarshal enrichment: %w", err)
		}
	}
	var riskReasons []string
	if len(row.RiskReasons) > 0 {
		if err := json.Unmarshal(row.RiskReasons, &riskReasons); err != nil {
			return nil, fmt.Errorf("unmarshal risk_reasons: %w", err)
		}
	}
	c := &discovery.SourceCandidate{
		ID:                row.ID,
		CanonicalURL:      row.CanonicalURL,
		IdentityKey:       row.IdentityKey,
		ReferringSourceID: row.ReferringSourceID,
		Enrichment:        enrichment,
		RiskScore:         row.RiskScore,
		RiskReasons:       riskReasons,
		Status:            discovery.CandidateStatus(row.Status),
		CreatedAt:         row.CreatedAt,
		UpdatedAt:         row.UpdatedAt,
	}
	if row.ApprovedAt != nil {
		c.ApprovedAt = row.ApprovedAt
	}
	if row.ApprovedBy != nil {
		c.ApprovedBy = *row.ApprovedBy
	}
	if row.CreatedSourceID != nil {
		c.CreatedSourceID = *row.CreatedSourceID
	}
	return c, nil
}

func nullEmpty(s string) *string {
	if s == "" {
		return nil
	}
	return &s
}

func isNoRows(err error) bool {
	return errors.Is(err, sql.ErrNoRows)
}
