version: '3'

dotenv: ['../.env']

vars:
  BINARY_NAME: integration
  MAIN_PATH: ./main.go
  BUILD_DIR: ./bin
  DOCKER_IMAGE: gopost-integration
  CONFIG_FILE: config.yml

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the integration service
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.MAIN_PATH}}
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  run:
    desc: Run the service locally
    deps: [deps]
    cmds:
      - go run {{.MAIN_PATH}} -config {{.CONFIG_FILE}}

  flush-cache:
    desc: Flush Redis deduplication cache
    deps: [deps]
    cmds:
      - go run {{.MAIN_PATH}} -config {{.CONFIG_FILE}} --flush-cache

  test:
    desc: "Run all tests"
    cmds:
      - go test -v ./...

  test:unit:
    desc: "Run unit tests"
    cmds:
      - go test -v ./internal/...

  test:integration:
    desc: "Run integration tests"
    cmds:
      - go test -v ./tests/integration/...

  test:coverage:
    desc: Run tests with coverage report
    deps: [deps]
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - 'echo "Coverage report generated: coverage.html"'

  test:race:
    desc: Run tests with race detector
    deps: [deps]
    cmds:
      - go test -race ./...

  clean:
    desc: Clean build artifacts and temporary files
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f coverage.out coverage.html
      - go clean -cache -testcache -modcache

  deps:
    desc: Download and tidy dependencies
    cmds:
      - go mod download
      - go mod tidy
      - go mod verify

  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...
      - goimports -w . || true

  tidy:
    desc: "Tidy go.mod and go.sum"
    cmds:
      - go mod tidy

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  lint:
    desc: "Lint the Go code"
    cmds:
      - go fmt ./...
      - go vet ./...
      - golangci-lint run

  check:
    desc: Run all code quality checks (fmt, vet, lint)
    cmds:
      - task: fmt
      - task: vet
      - task: lint

  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t {{.DOCKER_IMAGE}} .

  docker:build:dev:
    desc: "Build development Docker image"
    cmds:
      - docker build -f Dockerfile.dev -t {{.DOCKER_IMAGE}}:dev .

  docker:up:
    desc: Start services with Docker Compose
    cmds:
      - docker compose up -d

  docker:down:
    desc: Stop services
    cmds:
      - docker compose down

  docker:logs:
    desc: View integration service logs
    cmds:
      - docker compose logs -f integration

  docker:restart:
    desc: Restart Docker services
    cmds:
      - task: docker:down
      - task: docker:up

  dev:
    desc: Run in development mode with file watching (requires air or similar)
    cmds:
      - |
        if command -v air > /dev/null; then
          air
        else
          echo "air not installed. Install with: go install github.com/cosmtrek/air@latest"
          task: run
        fi

  install:tools:
    desc: "Install development tools"
    cmds:
      - go install github.com/air-verse/air@latest || true
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest || true
      - go install golang.org/x/tools/cmd/goimports@latest || true
      - go install github.com/golang-migrate/migrate/v4/cmd/migrate@latest || true

  migrate:up:
    desc: "Run database migrations up"
    env:
      PGPASSWORD: '{{.POSTGRES_PUBLISHER_PASSWORD | default ""}}'
    cmds:
      - |
        if [ -z "{{.POSTGRES_PUBLISHER_PASSWORD}}" ]; then
          echo "POSTGRES_PUBLISHER_PASSWORD environment variable not set"
          exit 1
        fi
      - |
        DB_HOST="{{.POSTGRES_PUBLISHER_HOST | default "localhost"}}"
        DB_PORT="{{.POSTGRES_PUBLISHER_PORT | default "5432"}}"
        DB_USER="{{.POSTGRES_PUBLISHER_USER | default "postgres"}}"
        DB_PASSWORD="{{.POSTGRES_PUBLISHER_PASSWORD}}"
        DB_NAME="{{.POSTGRES_PUBLISHER_DB | default "publisher"}}"
        DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"
        migrate -path ./internal/database/migrations -database "$DATABASE_URL" up

  migrate:down:
    desc: "Rollback last migration"
    env:
      PGPASSWORD: '{{.POSTGRES_PUBLISHER_PASSWORD | default ""}}'
    cmds:
      - |
        if [ -z "{{.POSTGRES_PUBLISHER_PASSWORD}}" ]; then
          echo "POSTGRES_PUBLISHER_PASSWORD environment variable not set"
          exit 1
        fi
      - |
        DB_HOST="{{.POSTGRES_PUBLISHER_HOST | default "localhost"}}"
        DB_PORT="{{.POSTGRES_PUBLISHER_PORT | default "5432"}}"
        DB_USER="{{.POSTGRES_PUBLISHER_USER | default "postgres"}}"
        DB_PASSWORD="{{.POSTGRES_PUBLISHER_PASSWORD}}"
        DB_NAME="{{.POSTGRES_PUBLISHER_DB | default "publisher"}}"
        DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"
        migrate -path ./internal/database/migrations -database "$DATABASE_URL" down 1

  migrate:version:
    desc: "Show current migration version"
    env:
      PGPASSWORD: '{{.POSTGRES_PUBLISHER_PASSWORD | default ""}}'
    cmds:
      - |
        if [ -z "{{.POSTGRES_PUBLISHER_PASSWORD}}" ]; then
          echo "POSTGRES_PUBLISHER_PASSWORD environment variable not set"
          exit 1
        fi
      - |
        DB_HOST="{{.POSTGRES_PUBLISHER_HOST | default "localhost"}}"
        DB_PORT="{{.POSTGRES_PUBLISHER_PORT | default "5432"}}"
        DB_USER="{{.POSTGRES_PUBLISHER_USER | default "postgres"}}"
        DB_PASSWORD="{{.POSTGRES_PUBLISHER_PASSWORD}}"
        DB_NAME="{{.POSTGRES_PUBLISHER_DB | default "publisher"}}"
        DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"
        migrate -path ./internal/database/migrations -database "$DATABASE_URL" version

  migrate:check:
    desc: "Check if migrations have been applied"
    env:
      PGPASSWORD: '{{.POSTGRES_PUBLISHER_PASSWORD | default ""}}'
    cmds:
      - |
        if [ -z "{{.POSTGRES_PUBLISHER_PASSWORD}}" ]; then
          echo "POSTGRES_PUBLISHER_PASSWORD environment variable not set"
          exit 1
        fi
      - |
        DB_HOST="{{.POSTGRES_PUBLISHER_HOST | default "localhost"}}"
        DB_PORT="{{.POSTGRES_PUBLISHER_PORT | default "5432"}}"
        DB_USER="{{.POSTGRES_PUBLISHER_USER | default "postgres"}}"
        DB_PASSWORD="{{.POSTGRES_PUBLISHER_PASSWORD}}"
        DB_NAME="{{.POSTGRES_PUBLISHER_DB | default "publisher"}}"
        DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"
        migrate -path ./internal/database/migrations -database "$DATABASE_URL" version || echo "No migrations applied yet. Run 'task migrate:up' to apply migrations."

  install:
    desc: Install the binary to $GOPATH/bin
    cmds:
      - go install {{.MAIN_PATH}}

  all:
    desc: Run build, test, and check
    cmds:
      - task: deps
      - task: check
      - task: test
      - task: build
