version: '3'

dotenv: ['../.env']

vars:
  BINARY_NAME: integration
  MAIN_PATH: ./main.go
  BUILD_DIR: ./bin
  DOCKER_IMAGE: gopost-integration
  CONFIG_FILE: config.yml

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the integration service
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.MAIN_PATH}}
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  run:
    desc: Run the service locally
    deps: [deps]
    cmds:
      - go run {{.MAIN_PATH}} -config {{.CONFIG_FILE}}

  flush-cache:
    desc: Flush Redis deduplication cache
    deps: [deps]
    cmds:
      - go run {{.MAIN_PATH}} -config {{.CONFIG_FILE}} --flush-cache

  test:
    desc: "Run all tests"
    cmds:
      - go test -v ./...

  test:unit:
    desc: "Run unit tests"
    cmds:
      - go test -v ./internal/...

  test:integration:
    desc: "Run integration tests"
    cmds:
      - go test -v ./tests/integration/...

  test:coverage:
    desc: Run tests with coverage report
    deps: [deps]
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - 'echo "Coverage report generated: coverage.html"'

  test:race:
    desc: Run tests with race detector
    deps: [deps]
    cmds:
      - go test -race ./...

  bench:
    desc: "Run benchmarks"
    cmds:
      - go test -bench=. -benchmem ./...

  bench:baseline:
    desc: "Capture performance baseline"
    cmds:
      - mkdir -p benchmarks
      - go test -bench=. -benchmem -benchtime=30s -count=5 ./... | tee benchmarks/baseline-{{now | date "2006-01-02"}}.txt
      - 'echo "Baseline captured: benchmarks/baseline-{{now | date "2006-01-02"}}.txt"'

  bench:compare:
    desc: "Compare current performance to baseline (requires benchstat)"
    cmds:
      - go test -bench=. -benchmem -benchtime=30s -count=5 ./... > benchmarks/current.txt
      - benchstat benchmarks/baseline-*.txt benchmarks/current.txt

  bench:profile:
    desc: "Run benchmarks with CPU and memory profiling"
    cmds:
      - mkdir -p profiles
      - go test -bench=. -cpuprofile=profiles/cpu.prof -memprofile=profiles/mem.prof ./...
      - 'echo "Profiles saved to profiles/ directory"'
      - 'echo "View CPU profile: go tool pprof -http=:8081 profiles/cpu.prof"'
      - 'echo "View memory profile: go tool pprof -http=:8081 profiles/mem.prof"'

  clean:
    desc: Clean build artifacts and temporary files
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f coverage.out coverage.html
      - go clean -cache -testcache -modcache

  deps:
    desc: Download and tidy dependencies
    cmds:
      - go mod download
      - go mod tidy
      - go mod verify

  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...
      - goimports -w . || true

  tidy:
    desc: "Tidy go.mod and go.sum"
    cmds:
      - go mod tidy

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  lint:
    desc: "Lint the Go code"
    cmds:
      - go fmt ./...
      - go vet ./...
      - golangci-lint run

  check:
    desc: Run all code quality checks (fmt, vet, lint)
    cmds:
      - task: fmt
      - task: vet
      - task: lint

  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t {{.DOCKER_IMAGE}} .

  docker:build:dev:
    desc: "Build development Docker image"
    cmds:
      - docker build -f Dockerfile.dev -t {{.DOCKER_IMAGE}}:dev .

  docker:up:
    desc: Start services with Docker Compose
    cmds:
      - docker compose up -d

  docker:down:
    desc: Stop services
    cmds:
      - docker compose down

  docker:logs:
    desc: View integration service logs
    cmds:
      - docker compose logs -f integration

  docker:restart:
    desc: Restart Docker services
    cmds:
      - task: docker:down
      - task: docker:up

  dev:
    desc: Run in development mode with file watching (requires air or similar)
    cmds:
      - |
        if command -v air > /dev/null; then
          air
        else
          echo "air not installed. Install with: go install github.com/cosmtrek/air@latest"
          task: run
        fi

  install:tools:
    desc: "Install development tools"
    cmds:
      - go install github.com/air-verse/air@latest || true
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest || true
      - go install golang.org/x/tools/cmd/goimports@latest || true
      - go install github.com/golang-migrate/migrate/v4/cmd/migrate@latest || true

  migrate:up:
    desc: "Run database migrations up"
    silent: true
    env:
      PGPASSWORD: '{{.POSTGRES_PUBLISHER_PASSWORD | default ""}}'
    cmds:
      - |
        if [ -z "{{.POSTGRES_PUBLISHER_PASSWORD}}" ]; then
          echo "POSTGRES_PUBLISHER_PASSWORD environment variable not set"
          exit 1
        fi
      - |
        DB_HOST="{{.POSTGRES_PUBLISHER_HOST | default "localhost"}}"
        DB_PORT="{{.POSTGRES_PUBLISHER_PORT | default "5432"}}"
        DB_USER="{{.POSTGRES_PUBLISHER_USER | default "postgres"}}"
        DB_PASSWORD="{{.POSTGRES_PUBLISHER_PASSWORD}}"
        DB_NAME="{{.POSTGRES_PUBLISHER_DB | default "publisher"}}"
        # Use Docker to run migration if connecting to containerized database
        if [ "$DB_HOST" = "localhost" ] && docker ps --format '{{.Names}}' | grep -q 'north-cloud-postgres-publisher'; then
          echo "Running migration via Docker (connecting to postgres-publisher container)..."
          docker run --rm --network north-cloud_north-cloud-network \
            -v "$(pwd)/internal/database/migrations:/migrations" \
            migrate/migrate:latest \
            -path /migrations \
            -database "postgres://${DB_USER}:${DB_PASSWORD}@postgres-publisher:5432/${DB_NAME}?sslmode=disable" \
            up
        else
          echo "Running migration via local connection..."
          DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"
          migrate -path ./internal/database/migrations -database "$DATABASE_URL" up
        fi

  migrate:down:
    desc: "Rollback last migration"
    silent: true
    env:
      PGPASSWORD: '{{.POSTGRES_PUBLISHER_PASSWORD | default ""}}'
    cmds:
      - |
        if [ -z "{{.POSTGRES_PUBLISHER_PASSWORD}}" ]; then
          echo "POSTGRES_PUBLISHER_PASSWORD environment variable not set"
          exit 1
        fi
      - |
        DB_HOST="{{.POSTGRES_PUBLISHER_HOST | default "localhost"}}"
        DB_PORT="{{.POSTGRES_PUBLISHER_PORT | default "5432"}}"
        DB_USER="{{.POSTGRES_PUBLISHER_USER | default "postgres"}}"
        DB_PASSWORD="{{.POSTGRES_PUBLISHER_PASSWORD}}"
        DB_NAME="{{.POSTGRES_PUBLISHER_DB | default "publisher"}}"
        # Use Docker to run migration if connecting to containerized database
        if [ "$DB_HOST" = "localhost" ] && docker ps --format '{{.Names}}' | grep -q 'north-cloud-postgres-publisher'; then
          echo "Running migration via Docker (connecting to postgres-publisher container)..."
          docker run --rm --network north-cloud_north-cloud-network \
            -v "$(pwd)/internal/database/migrations:/migrations" \
            migrate/migrate:latest \
            -path /migrations \
            -database "postgres://${DB_USER}:${DB_PASSWORD}@postgres-publisher:5432/${DB_NAME}?sslmode=disable" \
            down 1
        else
          echo "Running migration via local connection..."
          DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"
          migrate -path ./internal/database/migrations -database "$DATABASE_URL" down 1
        fi

  migrate:version:
    desc: "Show current migration version"
    silent: true
    env:
      PGPASSWORD: '{{.POSTGRES_PUBLISHER_PASSWORD | default ""}}'
    cmds:
      - |
        if [ -z "{{.POSTGRES_PUBLISHER_PASSWORD}}" ]; then
          echo "POSTGRES_PUBLISHER_PASSWORD environment variable not set"
          exit 1
        fi
      - |
        DB_HOST="{{.POSTGRES_PUBLISHER_HOST | default "localhost"}}"
        DB_PORT="{{.POSTGRES_PUBLISHER_PORT | default "5432"}}"
        DB_USER="{{.POSTGRES_PUBLISHER_USER | default "postgres"}}"
        DB_PASSWORD="{{.POSTGRES_PUBLISHER_PASSWORD}}"
        DB_NAME="{{.POSTGRES_PUBLISHER_DB | default "publisher"}}"
        DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"
        migrate -path ./internal/database/migrations -database "$DATABASE_URL" version

  migrate:check:
    desc: "Check if migrations have been applied"
    silent: true
    env:
      PGPASSWORD: '{{.POSTGRES_PUBLISHER_PASSWORD | default ""}}'
    cmds:
      - |
        if [ -z "{{.POSTGRES_PUBLISHER_PASSWORD}}" ]; then
          echo "POSTGRES_PUBLISHER_PASSWORD environment variable not set"
          exit 1
        fi
      - |
        DB_HOST="{{.POSTGRES_PUBLISHER_HOST | default "localhost"}}"
        DB_PORT="{{.POSTGRES_PUBLISHER_PORT | default "5432"}}"
        DB_USER="{{.POSTGRES_PUBLISHER_USER | default "postgres"}}"
        DB_PASSWORD="{{.POSTGRES_PUBLISHER_PASSWORD}}"
        DB_NAME="{{.POSTGRES_PUBLISHER_DB | default "publisher"}}"
        # Use Docker to run migration if connecting to containerized database
        if [ "$DB_HOST" = "localhost" ] && docker ps --format '{{.Names}}' | grep -q 'north-cloud-postgres-publisher'; then
          docker run --rm --network north-cloud_north-cloud-network \
            -v "$(pwd)/internal/database/migrations:/migrations" \
            migrate/migrate:latest \
            -path /migrations \
            -database "postgres://${DB_USER}:${DB_PASSWORD}@postgres-publisher:5432/${DB_NAME}?sslmode=disable" \
            version || echo "No migrations applied yet. Run 'task migrate:up' to apply migrations."
        else
          DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"
          migrate -path ./internal/database/migrations -database "$DATABASE_URL" version || echo "No migrations applied yet. Run 'task migrate:up' to apply migrations."
        fi

  install:
    desc: Install the binary to $GOPATH/bin
    cmds:
      - go install {{.MAIN_PATH}}

  all:
    desc: Run build, test, and check
    cmds:
      - task: deps
      - task: check
      - task: test
      - task: build
