#!/usr/bin/env python3
"""Generate ports + compose environment SSOT from merged Docker Compose models.

Compose merge and YAML parsing follow Docker Compose (same as runtime):
- Each compose input file is validated with PyYAML.
- Effective per-overlay config comes from `docker compose ... config --no-interpolate`.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError as e:  # pragma: no cover
    print("PyYAML is required: pip install -r scripts/ports-gen-requirements.txt", file=sys.stderr)
    raise e


ROOT = Path(__file__).resolve().parent.parent

OVERLAYS: dict[str, dict[str, Any]] = {
    # Dev stack: include optional profiles so ML + search + observability rows exist.
    "dev": {
        "files": ["docker-compose.base.yml", "docker-compose.dev.yml"],
        "extra_args": ["--profile", "ml", "--profile", "search", "--profile", "observability"],
    },
    "prod": {"files": ["docker-compose.base.yml", "docker-compose.prod.yml"], "extra_args": []},
    "test": {"files": ["docker-compose.base.yml", "docker-compose.test.yml"], "extra_args": []},
}

IPV4_RE = re.compile(r"^\d{1,3}(?:\.\d{1,3}){3}$")

NOTICE_LINES = [
    "<!--",
    "Generated by scripts/generate-ports-env-table.sh. Do not edit by hand.",
    "Run `task ports:generate` to refresh.",
    "-->",
    "",
    "## Ports and compose `environment` (SSOT)",
    "",
    "Axes:",
    "",
    "- **container_port** — port the service listens on *inside* the container (right-hand side of a `ports:` mapping).",
    "- **host_port** — published port on the Docker host (left-hand side), including `${VAR:-default}` literals when compose is not interpolated.",
    "- **bind_interface** — host bind address when the mapping is `ip:host:container`; empty when Docker defaults to all interfaces (`0.0.0.0`).",
    "- **env_vars** — keys from the merged compose `environment` mapping (sorted), plus `env_file:<path>` entries for each `env_file` reference.",
    "",
]


def validate_compose_yaml() -> None:
    for spec in OVERLAYS.values():
        for name in spec["files"]:
            path = ROOT / name
            with path.open(encoding="utf-8") as f:
                yaml.safe_load(f)


def run_compose_config(overlay: str) -> dict[str, Any]:
    spec = OVERLAYS[overlay]
    cmd: list[str] = ["docker", "compose"]
    for name in spec["files"]:
        cmd.extend(["-f", str(ROOT / name)])
    cmd.extend(spec["extra_args"])
    cmd.extend(
        [
            "config",
            "--format",
            "json",
            "--no-interpolate",
            "--no-env-resolution",
        ]
    )
    proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr or proc.stdout or "docker compose config failed\n")
        sys.exit(proc.returncode or 1)
    return json.loads(proc.stdout)


def port_tuple_from_compose_entry(entry: Any) -> tuple[str, str, str]:
    """Return (bind_interface, host_port_literal, container_port) for one published port."""
    if isinstance(entry, str):
        return split_port_spec(entry)
    if isinstance(entry, dict):
        pub = entry.get("published")
        tgt = entry.get("target")
        if pub is None or tgt is None:
            raise ValueError(f"unsupported port object: {entry!r}")
        host_ip = entry.get("host_ip") or ""
        bind = str(host_ip) if host_ip else ""
        host = str(pub)
        container = str(int(tgt)) if isinstance(tgt, (int, float)) else str(tgt)
        return bind, host, container
    raise TypeError(f"unsupported port entry type {type(entry)}: {entry!r}")


def split_port_spec(port_spec: str) -> tuple[str, str, str]:
    """Return (bind_interface, host_port_literal, container_port) from a ports: string."""
    spec = port_spec.split("/")[0]
    depth = 0
    last_colon = -1
    i = 0
    while i < len(spec):
        ch = spec[i]
        if ch == "$" and i + 1 < len(spec) and spec[i + 1] == "{":
            depth += 1
            i += 2
            continue
        if ch == "}" and depth > 0:
            depth -= 1
            i += 1
            continue
        if ch == ":" and depth == 0:
            last_colon = i
        i += 1
    if last_colon < 0:
        raise ValueError(f"unparseable ports entry: {port_spec!r}")
    left, right = spec[:last_colon], spec[last_colon + 1 :]
    if not right:
        raise ValueError(f"empty container port: {port_spec!r}")
    bind = ""
    host = left
    if left:
        first, _, rest = left.partition(":")
        if IPV4_RE.match(first) and rest != "":
            bind = first
            host = rest
    return bind, host, right


def env_keys_from_service(svc: dict[str, Any]) -> list[str]:
    keys: list[str] = []
    env = svc.get("environment")
    if isinstance(env, dict):
        keys.extend(str(k) for k in env)
    elif isinstance(env, list):
        for item in env:
            if not isinstance(item, str):
                continue
            if "=" in item:
                keys.append(item.split("=", 1)[0])
            else:
                keys.append(item)
    ef = svc.get("env_file")
    if isinstance(ef, str):
        keys.append(f"env_file:{ef}")
    elif isinstance(ef, list):
        for p in ef:
            if isinstance(p, str):
                keys.append(f"env_file:{p}")
    return sorted(set(keys))


def rows_for_overlay(overlay: str, model: dict[str, Any]) -> list[dict[str, Any]]:
    services = model.get("services") or {}
    out: list[dict[str, Any]] = []
    for name in sorted(services.keys()):
        svc = services[name] or {}
        raw_ports = svc.get("ports")
        env_vars = env_keys_from_service(svc)

        if raw_ports is None:
            out.append(
                {
                    "service": name,
                    "compose_overlay": overlay,
                    "container_port": None,
                    "host_port": None,
                    "bind_interface": None,
                    "env_vars": env_vars,
                }
            )
            continue

        if not isinstance(raw_ports, list):
            raise TypeError(f"{name}: ports must be list or null, got {type(raw_ports)}")

        if len(raw_ports) == 0:
            out.append(
                {
                    "service": name,
                    "compose_overlay": overlay,
                    "container_port": None,
                    "host_port": None,
                    "bind_interface": None,
                    "env_vars": env_vars,
                }
            )
            continue

        for entry in raw_ports:
            bind, host, container = port_tuple_from_compose_entry(entry)
            out.append(
                {
                    "service": name,
                    "compose_overlay": overlay,
                    "container_port": container,
                    "host_port": host if host != "" else None,
                    "bind_interface": bind if bind != "" else "",
                    "env_vars": env_vars,
                }
            )
    return out


def md_escape_cell(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ")


def render_markdown(rows: list[dict[str, Any]]) -> str:
    lines = NOTICE_LINES.copy()
    lines.append(
        "| service | compose_overlay | container_port | host_port | bind_interface | env_vars |"
    )
    lines.append("| --- | --- | --- | --- | --- | --- |")
    for r in rows:
        ev = ", ".join(md_escape_cell(x) for x in r["env_vars"])
        lines.append(
            "| "
            + " | ".join(
                [
                    md_escape_cell(str(r["service"])),
                    md_escape_cell(str(r["compose_overlay"])),
                    md_escape_cell("" if r["container_port"] is None else str(r["container_port"])),
                    md_escape_cell("" if r["host_port"] is None else str(r["host_port"])),
                    md_escape_cell(
                        ""
                        if r["bind_interface"] is None
                        else ("" if r["bind_interface"] == "" else str(r["bind_interface"]))
                    ),
                    ev or " ",
                ]
            )
            + " |"
        )
    lines.append("")
    lines.append("### Row index (grep-friendly)")
    lines.append("")
    for r in rows:
        cp = r["container_port"] if r["container_port"] is not None else "null"
        hp = r["host_port"] if r["host_port"] is not None else "null"
        bi = r["bind_interface"] if r["bind_interface"] is not None else "null"
        lines.append(
            f"- `{r['service']}|{r['compose_overlay']}|container_port={cp}|host_port={hp}|bind_interface={bi}`"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--out-md",
        type=Path,
        default=ROOT / "docs/generated/ports-and-env.md",
    )
    ap.add_argument(
        "--out-json",
        type=Path,
        default=ROOT / "docs/generated/ports-and-env.json",
    )
    args = ap.parse_args()

    validate_compose_yaml()

    all_rows: list[dict[str, Any]] = []
    for overlay in ("dev", "prod", "test"):
        model = run_compose_config(overlay)
        all_rows.extend(rows_for_overlay(overlay, model))

    all_rows.sort(
        key=lambda r: (
            {"dev": 0, "prod": 1, "test": 2}[str(r["compose_overlay"])],
            r["service"],
            str(r["container_port"] or ""),
            str(r["host_port"] or ""),
        )
    )

    doc = {
        "_meta": {
            "notice": (
                "Generated by scripts/generate-ports-env-table.sh. Do not edit by hand. "
                "Run `task ports:generate` to refresh."
            ),
        },
        "rows": all_rows,
    }

    args.out_md.parent.mkdir(parents=True, exist_ok=True)
    args.out_md.write_text(render_markdown(all_rows), encoding="utf-8")
    args.out_json.write_text(json.dumps(doc, indent=2, sort_keys=True) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
