// Package category defines the Category interface for AI observer analysis passes.
package category

import (
	"context"
	"time"

	"github.com/jonesrussell/north-cloud/ai-observer/internal/provider"
)

// Event is a normalized event from any data source (ES, Redis, Loki).
type Event struct {
	// Source identifier (domain, index name, sidecar name, etc.)
	Source string
	// Label is the primary classification label (topic, content_type, error_type, etc.)
	Label string
	// Confidence is the classifier confidence score (0.0-1.0). Zero if not applicable.
	Confidence float64
	// Timestamp of the event.
	Timestamp time.Time
	// Metadata holds category-specific fields.
	Metadata map[string]any
}

// Insight is a structured advisory generated by an LLM from a set of events.
type Insight struct {
	// Category that produced this insight.
	Category string
	// Severity: "low", "medium", "high".
	Severity string
	// Summary is a one-sentence human-readable description.
	Summary string
	// Details holds structured data supporting the insight.
	Details map[string]any
	// SuggestedActions is a list of actionable recommendations.
	SuggestedActions []string
	// TokensUsed is the total tokens consumed producing this insight.
	TokensUsed int
	// Model is the model that produced this insight.
	Model string
}

// Category is the interface all analysis categories must implement.
type Category interface {
	// Name returns the category identifier (e.g. "classifier", "sidecar", "ingestion").
	Name() string
	// Sample queries the data source and returns normalized events within the given window.
	Sample(ctx context.Context, window time.Duration) ([]Event, error)
	// Analyze runs the AI pass on the sampled events and returns insights.
	Analyze(ctx context.Context, events []Event, p provider.LLMProvider) ([]Insight, error)
	// MaxEventsPerRun returns the per-run event cap for this category.
	MaxEventsPerRun() int
	// ModelTier returns the preferred model tier: "haiku" or "sonnet".
	ModelTier() string
}
